[package]
name = "ds2-protocol"
version = "0.1.1"
edition = "2024"
rust-version = "1.85.0"
description = "no_std implementation of BMW's DS2 diagnostic protocol"
license = "MPL-2.0"
repository = "https://github.com/opetany93/ds2-protocol"
documentation = "https://docs.rs/ds2-protocol"
keywords = ["embedded", "bmw", "diagnostics", "kline", "ds2"]
categories = ["embedded", "no-std", "hardware-support"]

[dependencies]
